services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: dineflow-api

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      redis:
        condition: service_healthy

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: dineflow-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 5s
      timeout: 3s
      retries: 5