export const SYSTEM_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",

  RESTAURANT_OWNER: "RESTAURANT_OWNER",

  BRANCH_MANAGER: "BRANCH_MANAGER",

  CASHIER: "CASHIER",

  WAITER: "WAITER",

  CHEF: "CHEF",

  KITCHEN_STAFF: "KITCHEN_STAFF",
} as const;

export type SystemRole =
  (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];